<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurant;
use Illuminate\Support\Facades\DB;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        // Najpierw usuwamy wszystkie powiązania z tabeli answer_restaurant
        DB::table('answer_restaurant')->delete();

        // Następnie usuwamy wszystkie istniejące restauracje
        DB::table('restaurants')->delete();

        $restaurants = [
            [
                'name'     => 'Restauracja Konspira',
                'address'  => 'Rynek, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska',
                'rating'   => 4.5,
                'website'  => 'https://konspira.wroclaw.pl',
            ],
            [
                'name'     => 'Browar Stu Mostów',
                'address'  => 'ul. Ofiar Oświęcimskich 10/12, 50-061 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Pub / Browar',
                'rating'   => 4.2,
                'website'  => 'http://browarstumostow.pl',
            ],
            [
                'name'     => 'Pod Papugami',
                'address'  => 'Rynek 18, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Międzynarodowa',
                'rating'   => 4.0,
                'website'  => 'http://podpapugami.pl',
            ],
            [
                'name'     => 'Pizza Dominium',
                'address'  => 'ul. Świdnicka 35, 50-077 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Pizza',
                'rating'   => 4.1,
                'website'  => 'https://dominium.pl',
            ],
            [
                'name'     => 'Sushi Zushi',
                'address'  => 'ul. Legnicka 21, 50-056 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Sushi',
                'rating'   => 4.3,
                'website'  => 'https://sushizushi.pl',
            ],
            [
                'name'     => 'Kurna Chata',
                'address'  => 'ul. Wita Stwosza 8, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska',
                'rating'   => 4.0,
                'website'  => 'http://kurnachata.pl',
            ],
            [
                'name'     => 'Ramen Shop',
                'address'  => 'ul. Piłsudskiego 12, 50-093 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Ramen',
                'rating'   => 4.4,
                'website'  => 'http://ramenshop.pl',
            ],
            [
                'name'     => 'Pierogarnia Stary Młyn',
                'address'  => 'ul. Krupnicza 13, 50-001 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Pierogi, Polska',
                'rating'   => 4.2,
                'website'  => 'http://pierogarnia-starymlyn.pl',
            ],
            [
                'name'     => 'Restauracja Przystań',
                'address'  => 'ul. Oławska 9, 50-108 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Międzynarodowa',
                'rating'   => 4.0,
                'website'  => 'http://restauracjaprzystan.pl',
            ],
            [
                'name'     => 'Królikarnia',
                'address'  => 'ul. Katedralna 15, 50-100 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Grill',
                'rating'   => 4.3,
                'website'  => 'http://krolikarnia.pl',
            ],
            [
                'name'     => 'Merak',
                'address'  => 'ul. Świdnicka 10, 50-077 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Turecka, Kebab',
                'rating'   => 4.2,
                'website'  => 'http://merak.pl',
            ],
            [
                'name'     => 'Kebab King',
                'address'  => 'ul. Kuźnicza 20, 50-005 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Kebab',
                'rating'   => 4.1,
                'website'  => 'http://kebabking.pl',
            ],
            [
                'name'     => 'Thai Corner',
                'address'  => 'ul. Piłsudskiego 34, 50-092 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Tajska',
                'rating'   => 4.4,
                'website'  => 'http://thaicorner.pl',
            ],
            [
                'name'     => 'Chińczyk',
                'address'  => 'ul. Reja 11, 50-029 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Chińska',
                'rating'   => 4.0,
                'website'  => 'http://chinczyk.pl',
            ],
            [
                'name'     => 'La Maddalena',
                'address'  => 'ul. Świdnicka 2, 50-077 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Włoska',
                'rating'   => 4.3,
                'website'  => 'http://lamaddalena.pl',
            ],
            [
                'name'     => 'Bistro Racławicka',
                'address'  => 'ul. Racławicka 15, 50-031 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Bistro, Polska',
                'rating'   => 4.2,
                'website'  => 'http://bistro-raclawicka.pl',
            ],
            [
                'name'     => 'Central Cafe',
                'address'  => 'ul. Centralna 8, 50-061 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Kawiarnia, Bistro',
                'rating'   => 4.0,
                'website'  => 'http://centralcafe.pl',
            ],
            [
                'name'     => 'Stary Młyn',
                'address'  => 'ul. Młynarska 5, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska',
                'rating'   => 4.1,
                'website'  => 'http://starymlyn.pl',
            ],
            [
                'name'     => 'Francuska Pasja',
                'address'  => 'ul. Francuska 3, 50-050 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Francuska',
                'rating'   => 4.3,
                'website'  => 'http://francuskapasja.pl',
            ],
            [
                'name'     => 'Okrąglak',
                'address'  => 'ul. Okrąglak 12, 50-055 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Międzynarodowa',
                'rating'   => 4.2,
                'website'  => 'http://okraglak.pl',
            ],
            [
                'name'     => 'Dwa Kucharze',
                'address'  => 'ul. Kucharzy 7, 50-067 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Międzynarodowa',
                'rating'   => 4.1,
                'website'  => 'http://dwakucharze.pl',
            ],
            [
                'name'     => 'Bistro Złota Rybka',
                'address'  => 'ul. Rybna 9, 50-080 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Ryby, Kuchnia morska',
                'rating'   => 4.4,
                'website'  => 'http://zlota-rybka.pl',
            ],
            [
                'name'     => 'Złoty Smok',
                'address'  => 'ul. Smocza 11, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Chińska',
                'rating'   => 4.3,
                'website'  => 'http://zlotysmok.pl',
            ],
            [
                'name'     => 'Czerwony Kapturek',
                'address'  => 'ul. Czerwona 2, 50-075 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Tematyczna',
                'rating'   => 4.0,
                'website'  => 'http://czerwonykapturek.pl',
            ],
            [
                'name'     => 'Bistro Ramen',
                'address'  => 'ul. Ramen 6, 50-100 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Ramen',
                'rating'   => 4.5,
                'website'  => 'http://bistro-ramen.pl',
            ],
            [
                'name'     => 'Burger Bar Wrocław',
                'address'  => 'ul. Burgera 15, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Burgery',
                'rating'   => 4.2,
                'website'  => 'http://burgerbarwroclaw.pl',
            ],
            [
                'name'     => 'Pizzeria Capricciosa',
                'address'  => 'ul. Pizzowa 4, 50-060 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Pizza',
                'rating'   => 4.3,
                'website'  => 'http://capricciosa.pl',
            ],
            [
                'name'     => 'Sushi Time',
                'address'  => 'ul. Sushi 8, 50-078 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Sushi',
                'rating'   => 4.4,
                'website'  => 'http://sushitime.pl',
            ],
            [
                'name'     => 'Restauracja Wrocławskie Smaki',
                'address'  => 'ul. Smakoszy 10, 50-091 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska',
                'rating'   => 4.1,
                'website'  => 'http://wroclawskiesmaki.pl',
            ],
            [
                'name'     => 'Restauracja Stara Rzeka',
                'address'  => 'ul. Rzeczna 7, 50-123 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Ryby',
                'rating'   => 4.2,
                'website'  => 'http://stararzeka.pl',
            ],
            [
                'name'     => 'Pizza & Pasta',
                'address'  => 'ul. Włoska 9, 50-110 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Włoska',
                'rating'   => 4.3,
                'website'  => 'http://pizzaepasta.pl',
            ],
            [
                'name'     => 'Bistro Oriental',
                'address'  => 'ul. Orientalna 5, 50-115 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Orientalna, Azjatycka',
                'rating'   => 4.4,
                'website'  => 'http://bistrooriental.pl',
            ],
            [
                'name'     => 'Pierogarnia u Kowala',
                'address'  => 'ul. Kowalska 2, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Pierogi, Polska',
                'rating'   => 4.2,
                'website'  => 'http://pierogarniaukowala.pl',
            ],
            [
                'name'     => 'Bistro Italian Style',
                'address'  => 'ul. Włoska 12, 50-112 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Włoska',
                'rating'   => 4.3,
                'website'  => 'http://bistroitalianstyle.pl',
            ],
            [
                'name'     => 'Bistro Aroma',
                'address'  => 'ul. Aromatyczna 3, 50-093 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Kawiarnia, Bistro',
                'rating'   => 4.1,
                'website'  => 'http://bistroaroma.pl',
            ],
            [
                'name'     => 'Bistro U Kucharza',
                'address'  => 'ul. Kucharza 4, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Bistro',
                'rating'   => 4.0,
                'website'  => 'http://bistroukucharza.pl',
            ],
            [
                'name'     => 'Bistro Modern',
                'address'  => 'ul. Nowoczesna 7, 50-115 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Fusion, Nowoczesna',
                'rating'   => 4.2,
                'website'  => 'http://bistromodern.pl',
            ],
            [
                'name'     => 'Bistro Green',
                'address'  => 'ul. Zielona 10, 50-098 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Wegetariańska, Zdrowa',
                'rating'   => 4.3,
                'website'  => 'http://bistrogreen.pl',
            ],
            [
                'name'     => 'Bistro Vegan',
                'address'  => 'ul. Weganka 5, 50-100 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Wegańska',
                'rating'   => 4.2,
                'website'  => 'http://bistrovegan.pl',
            ],
            [
                'name'     => 'Bistro Mexican',
                'address'  => 'ul. Meksykańska 8, 50-105 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Meksykańska',
                'rating'   => 4.4,
                'website'  => 'http://bistromexican.pl',
            ],
            [
                'name'     => 'Bistro China Town',
                'address'  => 'ul. Chińska 7, 50-099 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Chińska',
                'rating'   => 4.1,
                'website'  => 'http://bistrochinatown.pl',
            ],
            [
                'name'     => 'Bistro Thai',
                'address'  => 'ul. Tajska 3, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Tajska',
                'rating'   => 4.3,
                'website'  => 'http://bistrothai.pl',
            ],
            [
                'name'     => 'Bistro Moja Kuchnia',
                'address'  => 'ul. Kucharska 9, 50-102 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska, Fusion',
                'rating'   => 4.2,
                'website'  => 'http://bistromojakuchnia.pl',
            ],
            [
                'name'     => 'Bistro Rozmaitości',
                'address'  => 'ul. Różnorodna 11, 50-104 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Różne',
                'rating'   => 4.1,
                'website'  => 'http://bistrorozmaitosci.pl',
            ],
            [
                'name'     => 'Bistro Fusion',
                'address'  => 'ul. Fuzji 6, 50-110 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Fusion',
                'rating'   => 4.4,
                'website'  => 'http://bistrofusion.pl',
            ],
            [
                'name'     => 'Kawiarnia Wroclaw Cafe',
                'address'  => 'ul. Kawiarniana 2, 50-106 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Kawiarnia',
                'rating'   => 4.0,
                'website'  => 'http://wroclawcafe.pl',
            ],
            [
                'name'     => 'Restauracja Artystyczna',
                'address'  => 'ul. Artystyczna 8, 50-107 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Międzynarodowa',
                'rating'   => 4.3,
                'website'  => 'http://restauracjaartystyczna.pl',
            ],
            [
                'name'     => 'Restauracja Zielona',
                'address'  => 'ul. Zielona 12, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Zdrowa, Wegetariańska',
                'rating'   => 4.2,
                'website'  => 'http://restauracjazielona.pl',
            ],
            [
                'name'     => 'Restauracja U Smakoszy',
                'address'  => 'ul. Smakoszy 3, 50-108 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Polska',
                'rating'   => 4.1,
                'website'  => 'http://usmakoszy.pl',
            ],
            [
                'name'     => 'Restauracja Na Rynku',
                'address'  => 'Rynek, 50-101 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Międzynarodowa',
                'rating'   => 4.0,
                'website'  => 'http://restauracjanarynku.pl',
            ],
            // Popularne restauracje z TikToka
            [
                'name'     => 'Pasibus',
                'address'  => 'ul. Świdnicka 11, 50-066 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Burgery',
                'rating'   => 4.7,
                'website'  => 'https://pasibus.pl',
                'description' => 'Kultowe burgery z Wrocławia, które podbiły serca mieszkańców i turystów. Pasibus słynie z soczystych burgerów z wysokiej jakości wołowiny i autorskich sosów.',
                'image_url' => 'https://example.com/images/pasibus.jpg',
                'price_level' => 2.5,
                'is_tiktok_recommended' => true,
                'popularity_score' => 95,
            ],
            [
                'name'     => 'Panczo',
                'address'  => 'ul. Św. Antoniego 35, 50-073 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Meksykańska',
                'rating'   => 4.6,
                'website'  => 'https://panczo.pl',
                'description' => 'Autentyczna kuchnia meksykańska w sercu Wrocławia. Panczo oferuje pyszne tacos, burrito i quesadillas, a także szeroki wybór tequili i koktajli.',
                'image_url' => 'https://example.com/images/panczo.jpg',
                'price_level' => 2.8,
                'is_tiktok_recommended' => true,
                'popularity_score' => 90,
            ],
            [
                'name'     => 'Kohana Sushi Bar',
                'address'  => 'ul. Agrestowa 142, 52-200 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Japońska, Sushi',
                'rating'   => 4.8,
                'website'  => 'https://kohanasushi.pl',
                'description' => 'Najlepsze sushi we Wrocławiu według wielu recenzji. Kohana Sushi Bar oferuje świeże, wysokiej jakości sushi przygotowywane przez doświadczonych kucharzy.',
                'image_url' => 'https://example.com/images/kohana.jpg',
                'price_level' => 3.5,
                'is_tiktok_recommended' => true,
                'popularity_score' => 88,
            ],
            [
                'name'     => 'Giro',
                'address'  => 'ul. Krakowska 182, 50-428 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Włoska, Pizza',
                'rating'   => 4.7,
                'website'  => 'https://giro.pizza',
                'description' => 'Autentyczna włoska pizzeria z piecem opalanym drewnem. Giro słynie z cienkiego, chrupiącego ciasta i wysokiej jakości składników sprowadzanych prosto z Włoch.',
                'image_url' => 'https://example.com/images/giro.jpg',
                'price_level' => 3.0,
                'is_tiktok_recommended' => true,
                'popularity_score' => 85,
            ],
            [
                'name'     => 'Neobab',
                'address'  => 'ul. Reja 47, 50-343 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Kebab, Turecka',
                'rating'   => 4.5,
                'website'  => 'https://neobab.pl',
                'description' => 'Nowoczesny kebab z najwyższej jakości składników. Neobab wyróżnia się na tle innych kebabów we Wrocławiu dzięki wysokiej jakości mięsu i świeżym dodatkom.',
                'image_url' => 'https://example.com/images/neobab.jpg',
                'price_level' => 2.0,
                'is_tiktok_recommended' => true,
                'popularity_score' => 82,
            ],
            [
                'name'     => 'Krasnolód',
                'address'  => 'ul. Oławska 27, 50-123 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Lodziarnia, Desery',
                'rating'   => 4.9,
                'website'  => 'https://krasnolod.pl',
                'description' => 'Rzemieślnicze lody robione z naturalnych składników. Krasnolód oferuje szeroki wybór oryginalnych smaków, które zmieniają się sezonowo.',
                'image_url' => 'https://example.com/images/krasnolod.jpg',
                'price_level' => 2.2,
                'is_tiktok_recommended' => true,
                'popularity_score' => 94,
            ],
            [
                'name'     => 'Mio Gelato',
                'address'  => 'ul. Zwycięska 45, 53-033 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Lodziarnia, Włoska',
                'rating'   => 4.8,
                'website'  => 'https://mio-gelato.pl',
                'description' => 'Autentyczne włoskie gelato przygotowywane według tradycyjnych receptur. Mio Gelato oferuje bogaty wybór smaków, w tym opcje wegańskie.',
                'image_url' => 'https://example.com/images/mio-gelato.jpg',
                'price_level' => 2.3,
                'is_tiktok_recommended' => true,
                'popularity_score' => 89,
            ],
            [
                'name'     => 'Lody z Krzyckiej',
                'address'  => 'ul. Krzycka 1C, 53-020 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Lodziarnia, Desery',
                'rating'   => 4.7,
                'website'  => 'https://lodyzkrzyckiej.pl',
                'description' => 'Rzemieślnicze lody o nietuzinkowych smakach. Lody z Krzyckiej słyną z oryginalnych połączeń smaków i wysokiej jakości składników.',
                'image_url' => 'https://example.com/images/lody-z-krzyckiej.jpg',
                'price_level' => 2.1,
                'is_tiktok_recommended' => true,
                'popularity_score' => 86,
            ],
            [
                'name'     => 'Lody na Zawalnej',
                'address'  => 'ul. Zawalna 1b, 50-001 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Lodziarnia, Desery',
                'rating'   => 4.6,
                'website'  => 'https://lodynazawalnej.pl',
                'description' => 'Kultowa lodziarnia działająca od 1988 roku. Lody na Zawalnej to miejsce, które odwiedzają pokolenia wrocławian, słynące z tradycyjnych, kremowych lodów.',
                'image_url' => 'https://example.com/images/lody-na-zawalnej.jpg',
                'price_level' => 1.9,
                'is_tiktok_recommended' => true,
                'popularity_score' => 84,
            ],
            [
                'name'     => 'Shisha Lounge RS Storm',
                'address'  => 'ul. Traugutta 65/1a, 50-417 Wrocław',
                'city'     => 'Wrocław',
                'cuisine'  => 'Orientalna, Fusion',
                'rating'   => 4.5,
                'website'  => 'https://rs-storm.pl',
                'description' => 'Ekskluzywny lounge bar z szerokim wyborem fajek wodnych i koktajli. RS Storm oferuje również menu z potrawami kuchni orientalnej i fusion.',
                'image_url' => 'https://example.com/images/rs-storm.jpg',
                'price_level' => 4.0,
                'is_tiktok_recommended' => true,
                'popularity_score' => 91,
            ],
        ];

        foreach ($restaurants as $restaurant) {
            // Dodanie losowych wartości dopasowania dla każdej restauracji
            $restaurant['match_people_count'] = rand(0, 9);
            $restaurant['match_price_per_person'] = rand(0, 9);
            $restaurant['match_meal_type'] = rand(0, 9);
            $restaurant['match_visit_purpose'] = rand(0, 9);
            $restaurant['match_dietary_preferences'] = rand(0, 9);

            Restaurant::create($restaurant);
        }
    }
}
